# Generated by Django 6.0 on 2025-12-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images_uploaded\\default.png",
                null=True,
                upload_to="images_uploaded/",
            ),
        ),
        migrations.CreateModel(
            name="BusinessGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="business_gallery/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Galleries",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
