# Generated by Django 5.1.7 on 2025-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('food', 'Food')], default='medical', max_length=20),
        ),
    ]
