# Generated by Django 5.1.7 on 2025-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media\\images_uploaded\\default.png', null=True, upload_to='images_uploaded/'),
        ),
    ]
